

import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*


**********




*/

/**
 *
 * @author ardas
 */
public class Kitap_ekrani extends javax.swing.JDialog {

    DefaultTableModel model;
    
    KutuphaneIslemleri islemler = new KutuphaneIslemleri();
    
    /**
     * Creates new form Kitap_ekrani
     */
    public Kitap_ekrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        model = (DefaultTableModel) kitap_tablosu.getModel();
        
        kitapGoruntule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kitap_tablosu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        arama_cubugu = new javax.swing.JTextField();
        kitap_alt_adi_alani = new javax.swing.JTextField();
        kitap_seri_adi_alani = new javax.swing.JTextField();
        yazar_alani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        yayın_evi_alani = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Isbn_no_alani = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        aciklama_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kitap_ekle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kitap_adi_alani = new javax.swing.JTextField();
        güncelle_buton = new javax.swing.JButton();
        kitap_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 200, 0, 0));

        kitap_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Kitap Adı", "Kitap Alt Adı", "Kitap Seri Adı", "Yazar", "Yayın Evi", "Isbn No", "Açıklama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kitap_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitap_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kitap_tablosu);
        if (kitap_tablosu.getColumnModel().getColumnCount() > 0) {
            kitap_tablosu.getColumnModel().getColumn(0).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(1).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(2).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(3).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(4).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(5).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(6).setResizable(false);
            kitap_tablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        kitap_seri_adi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_seri_adi_alaniActionPerformed(evt);
            }
        });

        jLabel1.setText("Kitap Adı : ");

        jLabel2.setText("Kitap Alt Adı :");

        jLabel3.setText("Kitap Seri Adı : ");

        jLabel4.setText("Yazar : ");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        jLabel5.setText("Yayın Evi : ");

        kitap_ekle.setText("Yeni Kitap Ekle");
        kitap_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_ekleActionPerformed(evt);
            }
        });

        jLabel6.setText("Isbn No : ");

        jLabel7.setText("Açıklama : ");

        güncelle_buton.setText("Güncelle");
        güncelle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelle_butonActionPerformed(evt);
            }
        });

        kitap_sil.setText("Kitap Sil");
        kitap_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(arama_cubugu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(kitap_alt_adi_alani))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(kitap_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kitap_seri_adi_alani)
                                    .addComponent(yazar_alani)
                                    .addComponent(yayın_evi_alani)
                                    .addComponent(Isbn_no_alani)
                                    .addComponent(aciklama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitap_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(güncelle_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kitap_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kitap_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitap_ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kitap_alt_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güncelle_buton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kitap_seri_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitap_sil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yazar_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(yayın_evi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Isbn_no_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(aciklama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        kitap_tablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        // TODO add your handling code here:
        
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
        
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void kitap_seri_adi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_seri_adi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitap_seri_adi_alaniActionPerformed

    private void kitap_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_ekleActionPerformed

        mesaj_yazisi.setText("");

        String kitapAd = kitap_adi_alani.getText();
        String kitapAltAd = kitap_alt_adi_alani.getText();
        String kitapSeriAd = kitap_seri_adi_alani.getText();
        String yazar = yazar_alani.getText();
        String yayınEvi = yayın_evi_alani.getText();
        String Isbn_no = Isbn_no_alani.getText();
        int IsbnNo = Integer.parseInt(Isbn_no);
        String aciklama = aciklama_alani.getText();

        islemler.kitapEkle(kitapAd,kitapAltAd,kitapSeriAd,yazar,yayınEvi,IsbnNo,aciklama);

        kitapGoruntule();

        mesaj_yazisi.setText("Yeni kitap başarıyla eklendi");

    }//GEN-LAST:event_kitap_ekleActionPerformed

    private void kitap_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitap_tablosuMouseClicked
        // TODO add your handling code here:
        
        int selectedrow = kitap_tablosu.getSelectedRow();
        
        
        
        kitap_adi_alani.setText(model.getValueAt(selectedrow, 1).toString());
        
        kitap_alt_adi_alani.setText(model.getValueAt(selectedrow, 2).toString());
        
        kitap_seri_adi_alani.setText(model.getValueAt(selectedrow, 3).toString());
        
        yazar_alani.setText(model.getValueAt(selectedrow, 4).toString());
        
        yayın_evi_alani.setText(model.getValueAt(selectedrow, 5).toString());
        
        Isbn_no_alani.setText(model.getValueAt(selectedrow, 6).toString());
        
        aciklama_alani.setText(model.getValueAt(selectedrow, 7).toString());
        
    }//GEN-LAST:event_kitap_tablosuMouseClicked

    private void güncelle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelle_butonActionPerformed
        // TODO add your handling code here:
        
        
        
        String kitapAdiAlani = kitap_adi_alani.getText();
        
        String kitapAltAdiAlani = kitap_alt_adi_alani.getText();
        
        String kitapSeriAdiAlani = kitap_seri_adi_alani.getText();
        
        String yazarAlani = yazar_alani.getText();
        
        String yayinEviAlani = yayın_evi_alani.getText();
        
        String IsbnNoAl = Isbn_no_alani.getText();
        
        int IsbnNoAlani = Integer.parseInt(IsbnNoAl);
        
        String aciklamaAlani = aciklama_alani.getText();
        
        
        
        
        
        int selectedrow = kitap_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount()==0){
                
                mesaj_yazisi.setText("Kitap Tablosu Şuanda Boş");
                
            }else{
                
                mesaj_yazisi.setText("Lütfen güncellemek için bir Kitap seçin");
                
            }
            
        }else{
            
            int id = (int) model.getValueAt(selectedrow, 0);
            
            islemler.kitapGuncelle(id,kitapAdiAlani,kitapAltAdiAlani,kitapSeriAdiAlani,yazarAlani,yayinEviAlani,IsbnNoAlani,aciklamaAlani);
            
            kitapGoruntule();
            
            mesaj_yazisi.setText("Kitap Başarıyla Güncellendi");
        }
        
    }//GEN-LAST:event_güncelle_butonActionPerformed

    private void kitap_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_silActionPerformed
        // TODO add your handling code here:
        
        mesaj_yazisi.setText("");
        
        int selectedrow = kitap_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount()==0){
                
                mesaj_yazisi.setText("Kitap Tablosu Şuanda Boş...");
                
            }
            
            else{
                
                mesaj_yazisi.setText("Lütfen silmek için bir kitap seçin...");
                
            }
            
        }else{
            
            int id = (int) model.getValueAt(selectedrow, 0);
            
            islemler.kitapSil(id);
            
            kitapGoruntule();
            
            mesaj_yazisi.setText("Kitap Başarıyla Silindi");
            
        }
        
    }//GEN-LAST:event_kitap_silActionPerformed
/*
    */
    
    
    
    /**
     * @param args the command line arguments
     */
    
    public void kitapGoruntule(){
        
        
        model.setRowCount(0);
        
        ArrayList<Kitap> kitapList = new ArrayList<Kitap>();
        
        kitapList = islemler.kitapGetir();
        
        if (kitapList!=null){
            
            for(Kitap kitap : kitapList){
                
                Object[] eklenecek = {kitap.getId(),kitap.getKitap_adı(),kitap.getKitap_alt_adı(),kitap.getKitap_seri_adı(),kitap.getYazar(),kitap.getYayın_evi(),kitap.getIsbn_no(),kitap.getAciklama()};
                
                model.addRow(eklenecek);
                
            }
            
        }
        
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kitap_ekrani dialog = new Kitap_ekrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Isbn_no_alani;
    private javax.swing.JTextField aciklama_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton güncelle_buton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kitap_adi_alani;
    private javax.swing.JTextField kitap_alt_adi_alani;
    private javax.swing.JButton kitap_ekle;
    private javax.swing.JTextField kitap_seri_adi_alani;
    private javax.swing.JButton kitap_sil;
    private javax.swing.JTable kitap_tablosu;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField yayın_evi_alani;
    private javax.swing.JTextField yazar_alani;
    // End of variables declaration//GEN-END:variables
}
