
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ardas
 */
public class Yayin_evi_ekrani extends javax.swing.JDialog {
    
   
    

    DefaultTableModel model;
    
    KutuphaneIslemleri islemler = new KutuphaneIslemleri();
    
    /**
     * Creates new form Yayin_evi_ekrani
     */
    public Yayin_evi_ekrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        model = (DefaultTableModel) yayın_evi_tablosu.getModel();
        
        yayinEviGoruntule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yayın_evi_tablosu = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yayın_evi_ad_alani = new javax.swing.JTextField();
        aciklama_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        yayin_evi_ekle_buton = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        yayin_evi_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 200, 0, 0));

        yayın_evi_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Yayın Evi Adı", "Açıklama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        yayın_evi_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yayın_evi_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(yayın_evi_tablosu);
        if (yayın_evi_tablosu.getColumnModel().getColumnCount() > 0) {
            yayın_evi_tablosu.getColumnModel().getColumn(0).setResizable(false);
            yayın_evi_tablosu.getColumnModel().getColumn(1).setResizable(false);
            yayın_evi_tablosu.getColumnModel().getColumn(2).setResizable(false);
        }

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Yayın Evi Adı :");

        jLabel2.setText("Açıklama : ");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        yayin_evi_ekle_buton.setText("Yayın Evi Ekle");
        yayin_evi_ekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yayin_evi_ekle_butonActionPerformed(evt);
            }
        });

        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        yayin_evi_sil.setText("Yayın Evi Sil");
        yayin_evi_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yayin_evi_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addComponent(arama_cubugu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(yayın_evi_ad_alani)
                            .addComponent(aciklama_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yayin_evi_ekle_buton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yayin_evi_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yayın_evi_ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yayin_evi_ekle_buton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aciklama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle))
                .addGap(18, 18, 18)
                .addComponent(yayin_evi_sil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        yayın_evi_tablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
        
        
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void yayin_evi_ekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yayin_evi_ekle_butonActionPerformed
        // TODO add your handling code here:
        
        mesaj_yazisi.setText("");
        
        String yayinEviAlani = yayın_evi_ad_alani.getText();
        
        String aciklamaAlani = aciklama_alani.getText();
        
        islemler.yayinEviEkle(yayinEviAlani,aciklamaAlani);
        
        yayinEviGoruntule();
        
        mesaj_yazisi.setText("Yeni yayın evi eklendi");
        
    }//GEN-LAST:event_yayin_evi_ekle_butonActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        // TODO add your handling code here:
        
        String yayinEviAdiAlani = yayın_evi_ad_alani.getText();
        
        String aciklamaAlani = aciklama_alani.getText();
        
        
        
        
        
        int selectedrow = yayın_evi_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount()==0){
                
                mesaj_yazisi.setText("Yayın Evi Tablosu Tablosu Şuanda Boş");
                
            }else{
                
                mesaj_yazisi.setText("Lütfen güncellemek için bir Yayın Evi seçiniz");
                
            }
            
        }else{
            
            int id = (int) model.getValueAt(selectedrow, 0);
            
            islemler.yayinEviGuncelle(id,yayinEviAdiAlani,aciklamaAlani);
            
            yayinEviGoruntule();
            
            mesaj_yazisi.setText("Yayın Evi Başarıyla Güncellendi");
        }
        
    }//GEN-LAST:event_guncelleActionPerformed

    private void yayın_evi_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yayın_evi_tablosuMouseClicked
        // TODO add your handling code here:
        
        int selectedrow = yayın_evi_tablosu.getSelectedRow();
        
        yayın_evi_ad_alani.setText(model.getValueAt(selectedrow, 1).toString());
        
        aciklama_alani.setText(model.getValueAt(selectedrow, 2).toString());
        
    }//GEN-LAST:event_yayın_evi_tablosuMouseClicked

    private void yayin_evi_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yayin_evi_silActionPerformed
        // TODO add your handling code here:
        
        mesaj_yazisi.setText("");
        
        int selectedrow = yayın_evi_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            
            if(model.getRowCount()==0){
                
                mesaj_yazisi.setText("Yayın evi Tablosu Şuanda Boş...");
                
            }
            
            else{
                
                mesaj_yazisi.setText("Lütfen silmek için bir Yayın evi seçin...");
                
            }
            
        }else{
            
            int id = (int) model.getValueAt(selectedrow, 0);
            
            islemler.yayinEviSil(id);
            
            yayinEviGoruntule();
            
            mesaj_yazisi.setText("Yayın Evi Başarıyla Silindi");
            
        }
        
        
    }//GEN-LAST:event_yayin_evi_silActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void yayinEviGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<YayınEvi> yayinEviList = new ArrayList<YayınEvi>();
        
        yayinEviList = islemler.yayinEviGetir();
        
        if (yayinEviList!=null){
            
            for(YayınEvi yayınEvi : yayinEviList){
                
                Object[] eklenecek = {yayınEvi.getId(),yayınEvi.getYayın_evi_ad(),yayınEvi.getAciklama()};
                
                model.addRow(eklenecek);
                
            }
            
        }
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yayin_evi_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yayin_evi_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yayin_evi_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yayin_evi_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Yayin_evi_ekrani dialog = new Yayin_evi_ekrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aciklama_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton yayin_evi_ekle_buton;
    private javax.swing.JButton yayin_evi_sil;
    private javax.swing.JTextField yayın_evi_ad_alani;
    private javax.swing.JTable yayın_evi_tablosu;
    // End of variables declaration//GEN-END:variables
}
